apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: lestencrypt
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: prgomesr@gmail.com
    privateKeySecretRef:
      name: lestencrypt-tls
    solvers:
    - http01:
        ingress:
          class: nginx

