apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: goserver-pvc
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  #persistentVolumeReclaimPolicy: Recycle
  #storageClassName: slow
  #mountOptions:
  #  - hard
  #  - nfsvers=4.1
  #nfs:
  #  path: /tmp
  #  server: 172.17.0.2
