apiVersion: apps/v1
kind: ReplicaSet
metadata:
 name: goserver
 labels:
  app: goserver
spec:
 selector:
  matchLabels:
   app: goserver
 replicas: 2
 template:
  metadata:
    labels:
      app: "goserver"
  spec:
    containers:
      - name: goserver
        image: prgomesr/fc3-go-hello
